### ISSUE TITLE
Hash mismatch - can't install

### ISSUE THREAD

**Issue by asinghvi17** [JuliaBinaryWrappers/Libglvnd_jll.jl#1]
```
┌ Error: Hash Mismatch!
 │   Expected sha256:   442f58f4724dd6b11aed63700e23301d33275cdbd2293e42e1815e4729fa92f5
 │   Calculated sha256: c95e0e24efb36af5289651e8c3d6c111d090fd71181ccc13a6e79ea68123c202
 └ @ Pkg.PlatformEngines /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Pkg/src/PlatformEngines.jl:985
 ERROR: Unable to automatically install 'Libglvnd' from '/builds/JuliaGPU/MakieGallery-jl/.julia/packages/Libglvnd_jll/6Gg7K/Artifacts.toml'
```

**Comment by asinghvi17** [comment]
Looks like the new version hasn't been registered - cc @giordano.

**Comment by giordano** [comment]
Thanks, I was just waiting for the first report about this, it took about 12 hours.  So now I know for how long we can have something broken without no one noticing :slightly_smiling_face:

**Comment by asinghvi17** [comment]
Well you would have gotten away with it if not for us meddling kids 🤣 

Also, there is a fair amount of CI which relies on this, so the moment anyone touches that they'll see some breakage.

**Comment by giordano** [comment]
> Also, there is a fair amount of CI which relies on this, so the moment anyone touches that they'll see some breakage.

In fact I was super surprised that no one complained so far.  Especially since I also broke `Xorg_libX11` which should be even more popular than this one.

**Comment by asinghvi17** [comment]
I suspect you were somewhat helped by the timing - that was night in the US.

Also, I need that one too, this just happened to be first - pls fix

**Comment by giordano** [comment]
Fixed
